laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('perfil', 'PerfilController@index')->name('perfil');
    Route::get('produtos', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{categoria}', 'ProdutosController@show')->name('produtos.show');
    Route::get('produtos/list/{categoria}', 'ProdutosController@getProdutos')->name('produtos.getProdutos');
    Route::get('produtos/detalhe/{produto}', 'ProdutosController@showProduto')->name('produtos.showProduto');
    Route::get('colecoes', 'ColecoesController@index')->name('colecoes');
    Route::get('colecoes/{colecao}', 'ColecoesController@show')->name('colecoes.show');
    Route::get('colecoes/list/{colecao}', 'ColecoesController@getProdutos')->name('colecoes.getProdutos');
    Route::get('clipping', 'ClippingController@index')->name('clipping');
    Route::get('clipping/{id}', 'ClippingController@show')->name('clipping.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('banners', 'BannersController');
        Route::resource('institucional', 'InstitucionalController', ['only' => ['index', 'update']]);
        Route::resource('categorias', 'CategoriasController');
        Route::resource('colecoes', 'ColecoesController');
        Route::get('colecoes/{id}/produtos', 'ColecoesProdutosController@index')->name('painel.colecoes.produtos.index');
        Route::get('colecoes/{id}/produtos/create', 'ColecoesProdutosController@create')->name('painel.colecoes.produtos.create');
        Route::get('produtos/categoria/{categoria_id}', 'ColecoesProdutosController@getProdutoCategoria')->name('painel.colecoes.produtos.getProdutoCategoria');
        Route::post('colecoes/{id}/produtos/create', 'ColecoesProdutosController@store')->name('painel.colecoes.produtos.store');
        Route::delete('colecoes/{id}/produtos/delete/{produto}', 'ColecoesProdutosController@destroy')->name('painel.colecoes.produtos.destroy');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produtos}/variacoes/clear', [
            'as'   => 'painel.produtos.variacoes.clear',
            'uses' => 'ProdutosVariacoesController@clear'
        ]);
        Route::resource('produtos.variacoes', 'ProdutosVariacoesController', ['parameters' => ['variacoes' => 'variacoes_produtos']]);
        Route::resource('clipping', 'ClippingController');
        Route::get('clipping/{clipping}/imagens/clear', [
            'as'   => 'painel.clipping.imagens.clear',
            'uses' => 'ClippingImagensController@clear'
        ]);
        Route::resource('clipping.imagens', 'ClippingImagensController', ['parameters' => ['imagens' => 'imagens_clipping']]);
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\Banner;
use App\Http\Requests\BannersRequest;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriasRequest;
use App\Models\Categoria;

class CategoriasController extends Controller
{
    public function index()
    {
        $registros = Categoria::orderBy('titulo', 'asc')->get();

        return view('painel.categorias.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.categorias.create');
    }

    public function store(CategoriasRequest $request)
    {
        try {

            $input = $request->all();

            Categoria::create($input);

            return redirect()->route('painel.categorias.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Categoria $registro)
    {
        return view('painel.categorias.edit', compact('registro'));
    }

    public function update(CategoriasRequest $request, Categoria $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.categorias.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Categoria $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.categorias.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ClippingRequest;
use App\Models\Clipping;

class ClippingController extends Controller
{
    public function index()
    {
        $registros = Clipping::ordenados()->get();

        return view('painel.clipping.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.clipping.create');
    }

    public function store(ClippingRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Clipping::upload_imagem();

            Clipping::create($input);

            return redirect()->route('painel.clipping.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Clipping $registro)
    {
        return view('painel.clipping.edit', compact('registro'));
    }

    public function update(ClippingRequest $request, Clipping $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Clipping::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.clipping.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Clipping $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.clipping.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ClippingImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ClippingImagensRequest;
use App\Models\Clipping;
use App\Models\ClippingImagem;

class ClippingImagensController extends Controller
{
    public function index(Clipping $registro)
    {
        $imagens = ClippingImagem::clipping($registro->id)->ordenados()->get();

        return view('painel.clipping.imagens.index', compact('imagens', 'registro'));
    }

    public function show(Clipping $registro, ClippingImagem $imagem)
    {
        return $imagem;
    }

    public function store(Clipping $registro, ClippingImagensRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = ClippingImagem::uploadImagem();
            $input['clipping_id'] = $registro->id;

            $imagem = ClippingImagem::create($input);

            $view = view('painel.clipping.imagens.imagem', compact('registro', 'imagem'))->render();

            return response()->json(['body' => $view]);
        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: ' . $e->getMessage();
        }
    }

    public function destroy(Clipping $registro, ClippingImagem $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.clipping.imagens.index', $registro)
                ->with('success', 'Imagem excluída com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: ' . $e->getMessage()]);
        }
    }

    public function clear(Clipping $registro)
    {
        try {

            $registro->imagens()->delete();
            return redirect()->route('painel.clipping.imagens.index', $registro)
                ->with('success', 'Imagens excluídas com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagens: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ColecoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ColecoesRequest;
use App\Models\Colecao;

class ColecoesController extends Controller
{
    public function index()
    {
        $registros = Colecao::orderBy('titulo', 'desc')->get();

        return view('painel.colecoes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.colecoes.create');
    }

    public function store(ColecoesRequest $request)
    {
        try {

            $input = $request->all();

            Colecao::create($input);

            return redirect()->route('painel.colecoes.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Colecao $registro)
    {
        return view('painel.colecoes.edit', compact('registro'));
    }

    public function update(ColecoesRequest $request, Colecao $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.colecoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Colecao $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.colecoes.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ColecoesProdutosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Categoria;
use App\Models\Colecao;
use App\Models\ColecaoProdutos;
use App\Models\Produto;

class ColecoesProdutosController extends Controller
{
    public function index($id)
    {
        $colecao = Colecao::find($id);

        $produtosColecao = ColecaoProdutos::where('colecao_id', $colecao->id)->ordenados()->get();

        $produtos = [];
        $produtosC = [];

        foreach($produtosColecao as $p) {
            $produtos[] = Produto::where('id', $p->produto_id)->first();
            $produtosC[] = $p->id;
        }

        $categorias = Categoria::all();

        return view('painel.colecoes.produtos.index', compact('produtos', 'colecao', 'categorias', 'produtosColecao', 'produtosC'));
    }

    public function create($id)
    {
        $colecao = Colecao::find($id);

        $categorias = Categoria::orderBy('titulo', 'asc')->get();

        return view('painel.colecoes.produtos.create', compact('colecao', 'categorias'));
    }

    public function getProdutoCategoria($categoria_id)
    {
        $produtos = Produto::where('categoria_id', $categoria_id)->ordenados()->get();

        return response()->json($produtos);
    }

    public function store(ColecaoProdutos $registro, Request $request)
    {
        try {
            $input['colecao_id'] = $request->colecao_id;
            $input['produto_id'] = $request->produto_id;
            $input['capa_alternativa'] = $request->capa_alternativa;

            if (isset($input['capa_alternativa'])) $input['capa_alternativa'] = ColecaoProdutos::uploadAlternativa();

            $registro = ColecaoProdutos::create($input);

            return redirect()->route('painel.colecoes.produtos.index', $request->colecao_id)->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy($id, $produto)
    {
        try {
            $registro = ColecaoProdutos::where('produto_id', $produto)->where('colecao_id', $id)->first();

            if ($registro) {
                $registro->delete();
            }
            return redirect()->route('painel.colecoes.produtos.index', $id)->with('success', 'Produto excluído com sucesso.');
        } catch (\Exception $e) {
            
            return back()->withErrors(['Erro ao excluir produto: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/produtos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos /</small> Adicionar Produto</h2>
    </legend>

    {!! Form::open(['route' => 'painel.produtos.store', 'files' => true]) !!}

        @include('painel.produtos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos /</small> Editar Produto</h2>
    </legend>

    {!! Form::model($produto, [
        'route'  => ['painel.produtos.update', $produto->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.produtos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('categoria_id', 'Categoria') !!}
    {!! Form::select('categoria_id', $categorias , old('categoria_id'), ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem,', 'Imagem') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/produtos/'.$produto->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto', 'Texto') !!}
    {!! Form::textarea('texto', null, ['class' => 'form-control ckeditor', 'data-editor' => 'padrao']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.produtos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/produtos/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        Produtos
        <a href="{{ route('painel.produtos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Produto</a>
    </h2>
</legend>

<h4 class="titulo-categorias">Categorias:</h4>
<div class="lista-categorias">
    @foreach($categorias as $categoria)
    <a href="{{ route('painel.produtos.index', ['categoria' => $categoria->id]) }}" class="categoria {{ (isset($_GET['categoria']) && $_GET['categoria'] == $categoria->id) ? 'active' : '' }}">{{ $categoria->titulo }}</a>
    @endforeach
</div>

@if(!count($produtos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="produtos">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Título</th>
            <th>Imagens</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($produtos as $produto)
        <tr class="tr-row" id="{{ $produto->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td>{{ $produto->titulo }}</td>
            <td><a href="{{ route('painel.produtos.variacoes.index', $produto->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.produtos.destroy', $produto->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.produtos.edit', $produto->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection